# Generated by Django 4.1.7 on 2023-03-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakebox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='cakebox',
            name='layer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cakebox',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
